import requests
import json

url = "https://opac.lib.csu.edu.cn/find/physical/groupitems"

payload = {
  "page": 1,
  "rows": 10,
  "entrance": None,
  "recordId": "794724",
  "isUnify": True,
  "sortType": 0,
  "callNo": ""
}


headers = {
  'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36",
  'Accept': "application/json, text/plain, */*",
  'Accept-Encoding': "gzip, deflate, br, zstd",
  'sec-ch-ua-platform': "\"Linux\"",
  'sec-ch-ua': "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand\";v=\"24\"",
  'mappingPath': "",
  'groupCode': "800388",
  'sec-ch-ua-mobile': "?0",
  'x-lang': "CHI",
  'Content-Type': "application/json;charset=UTF-8",
  'content-language': "zh_CN",
  'Origin': "https://opac.lib.csu.edu.cn",
  'Sec-Fetch-Site': "same-origin",
  'Sec-Fetch-Mode': "cors",
  'Sec-Fetch-Dest': "empty",
  'Referer': "https://opac.lib.csu.edu.cn/",
  'Accept-Language': "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
}

response = requests.post(url, data=json.dumps(payload), headers=headers)

print(response.text)

"""
{
  "success": true,
  "message": "操作成功",
  "errCode": 200,
  "errorCode": null,
  "data": {
    "locationFlag": "1",
    "shelfmarkFlag": "1",
    "totalCount": 3,
    "list": [
      {
        "itemId": 2831014,
        "callNo": "TP392.092.2/LH",
        "barcode": "101134599",
        "propNo": "101134599",
        "libCode": "80038800001",
        "libName": "中南大学",
        "locationId": 31,
        "locationName": "天心校区馆-铁道书库",
        "realLocationName": "铁道书库",
        "curLocationId": 31,
        "curLocationName": "天心校区馆-铁道书库",
        "currencyCode": null,
        "listPrice": 79.0,
        "netPrice": 79.0,
        "year": "",
        "vol": "",
        "inDate": "2018-03-13",
        "processType": "在架",
        "itemPolicyCode": 2,
        "materialCode": 1,
        "getModeCode": 1,
        "circAttr": "0",
        "remark": "",
        "attachment": "",
        "shelfNo": "21架B面2列3层",
        "pol": -1,
        "operateFlag": null,
        "url": "",
        "address": null,
        "unionFlag": 0,
        "backGroupName": null,
        "donatorName": null,
        "locationAddress": "",
        "positionUrl": null,
        "itemPolicyName": "中文科技图书",
        "xyzShelfNo": "0/0/0",
        "wxMiniProgramPhysicalPositionUrl": "",
        "wxMiniProgramPhysicalPositionUsername": "",
        "urlName": null,
        "resourceExtendList": null,
        "showPositionByCmaLoc": 1,
        "requestable": null,
        "itemRequestType": null
      },
      {
        "itemId": 2876539,
        "callNo": "TP392.092.2/LH",
        "barcode": "101134601",
        "propNo": "101134601",
        "libCode": "80038800001",
        "libName": "中南大学",
        "locationId": 65,
        "locationName": "潇湘校区馆-新馆",
        "realLocationName": "新馆",
        "curLocationId": 65,
        "curLocationName": "潇湘校区馆-新馆",
        "currencyCode": null,
        "listPrice": 79.0,
        "netPrice": 79.0,
        "year": "",
        "vol": "",
        "inDate": "2018-03-13",
        "processType": "在架",
        "itemPolicyCode": 2,
        "materialCode": 1,
        "getModeCode": 1,
        "circAttr": "0",
        "remark": "",
        "attachment": "",
        "shelfNo": "",
        "pol": -1,
        "operateFlag": null,
        "url": "",
        "address": null,
        "unionFlag": 0,
        "backGroupName": null,
        "donatorName": null,
        "locationAddress": "",
        "positionUrl": null,
        "itemPolicyName": "中文科技图书",
        "xyzShelfNo": "0/0/0",
        "wxMiniProgramPhysicalPositionUrl": "",
        "wxMiniProgramPhysicalPositionUsername": "",
        "urlName": null,
        "resourceExtendList": null,
        "showPositionByCmaLoc": 1,
        "requestable": null,
        "itemRequestType": null
      },
      {
        "itemId": 2876538,
        "callNo": "TP392.092.2/LH",
        "barcode": "101134600",
        "propNo": "101134600",
        "libCode": "80038800001",
        "libName": "中南大学",
        "locationId": 65,
        "locationName": "潇湘校区馆-新馆",
        "realLocationName": "新馆",
        "curLocationId": 65,
        "curLocationName": "潇湘校区馆-新馆",
        "currencyCode": null,
        "listPrice": 79.0,
        "netPrice": 79.0,
        "year": "",
        "vol": "",
        "inDate": "2018-03-13",
        "processType": "在架",
        "itemPolicyCode": 2,
        "materialCode": 1,
        "getModeCode": 1,
        "circAttr": "0",
        "remark": "",
        "attachment": "",
        "shelfNo": "",
        "pol": -1,
        "operateFlag": null,
        "url": "",
        "address": null,
        "unionFlag": 0,
        "backGroupName": null,
        "donatorName": null,
        "locationAddress": "",
        "positionUrl": null,
        "itemPolicyName": "中文科技图书",
        "xyzShelfNo": "0/0/0",
        "wxMiniProgramPhysicalPositionUrl": "",
        "wxMiniProgramPhysicalPositionUsername": "",
        "urlName": null,
        "resourceExtendList": null,
        "showPositionByCmaLoc": 1,
        "requestable": null,
        "itemRequestType": null
      }
    ]
  }
}
"""